version: "2.1"
services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=obsidian
    volumes:
      - /var/www/obsidian/data:/opt/couchdb/data
      - /var/www/obsidian/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped
